name: setup-ollama
description: Set up GitHub Actions workflow with Ollama
author: remarkablemark
inputs:
  version:
    description: CLI version
    required: false
    default: 0.30.6
  name:
    description: CLI name
    required: false
    default: ollama
runs:
  using: node24
  main: dist/index.js
  pre: chainguard-phonehome.js
branding:
  icon: terminal
  color: gray-dark
